site_name: Cebraspe

repo_name: '2021.2-Cebraspe'
repo_url: 'https://github.com/Interacao-Humano-Computador/2021.2-Cebraspe'


nav:
  - Início: index.md
  - Planejamento: 
    - Ferramentas: Planejamento/Ferramentas/ferramentas.md
    - Sites Avaliados: Planejamento/Sites/sites.md
    - Metodologia Adotada: Planejamento/Metodologias/Metodologias.md
    - Cronograma do Projeto: Planejamento/Cronograma/Cronograma.md
    - Processo de Design: Planejamento/Processo/Processo.md
  - Apresentações:
    - Apresentação 1: Apresentacoes/Apresentacao1.md

theme:
  name: material
  language: 'pt'
