site_name: Cebraspe

repo_name: "2021.2-Cebraspe"
repo_url: "https://github.com/Interacao-Humano-Computador/2021.2-Cebraspe"

theme:
  name: material
  language: "pt"
  palette:
    primary: "#fff"
    accent: "light blue"
  font:
    text: "Montserrat"
    code: "sans-serif"
  logo: "Assets/logo.png"
  favicon: "Assets/logo.png"

nav:
  - Início: index.md
  - Planejamento:
      - Ferramentas: Planejamento/Ferramentas/ferramentas.md
      - Sites Avaliados: Planejamento/Sites/sites.md
      - Metodologia Adotada: Planejamento/Metodologias/Metodologias.md
      - Cronograma do Projeto: Planejamento/Cronograma/Cronograma.md
      - Processo de Design: Planejamento/Processo/Processo.md
  - Análise de Requisitos:
      - Perfil de usuário: Análise_de_requisitos/Perfil_do_usuario/perfil_do_usuario.md
      - Personas: Análise_de_requisitos/Personas/personas.md
      - Análise de Tarefas:
          - CTT: Análise_de_requisitos/Análise_de_tarefas/CTT.md
          - HTA: Análise_de_requisitos/Análise_de_tarefas/HTA.md
      - Princípios Gerais: Análise_de_requisitos/Principios_gerais/Principios_gerais.md
      - Guia de Estilo: Análise_de_requisitos/Guia_de_estilo/guia_de_estilo.md
      - Metas de Usabilidade: Análise_de_requisitos/Metas_de_usabilidade/metas_de_usabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
        - Análise de Tarefas:
          - Planejamento da avaliação de análise de tarefas: Avaliação_desenvolvimento/Nivel1/planejamento.md
          - Entrevista: Avaliação_desenvolvimento/Nivel1/entrevista.md
          - Avaliação de análise de Tarefas: Avaliação_desenvolvimento/Nivel1/avaliacao.md
        - Storyboard: 
          - Planejamento da Avaliação - Storyboard: Avaliação_desenvolvimento/Nivel1/planejamento_storyboard.md
          - Storyboard: Avaliação_desenvolvimento/Nivel1/Storyboard.md
          - Avaliação do Storyboard: Avaliação_desenvolvimento/Nivel1/avaliacao_storyboard.md
  - Apresentações:
      - Apresentação 1: Apresentacoes/Apresentacao1.md
      - Apresentação 2: Apresentacoes/Apresentacao2.md
      - Apresentação 3: Apresentacoes/Apresentacao3.md
      - Apresentação 4: Apresentacoes/Apresentacao4.md
  - Atas:
      - 23-02-2022: Atas/23-02-2022.md
      - 07-03-2022: Atas/07-03-2022.md
      - 14-03-2022: Atas/14-03-2022.md
