site_name: Cebraspe

repo_name: "2021.2-Cebraspe"
repo_url: "https://github.com/Interacao-Humano-Computador/2021.2-Cebraspe"

theme:
  name: material
  language: "pt"
  palette:
    primary: "#fff"
    accent: "light blue"
  font:
    text: "Montserrat"
    code: "sans-serif"
  logo: "Assets/logo.png"
  favicon: "Assets/logo.png"

nav:
  - Início: index.md
  - Planejamento:
      - Ferramentas: Planejamento/Ferramentas/ferramentas.md
      - Sites Avaliados: Planejamento/Sites/sites.md
      - Metodologia Adotada: Planejamento/Metodologias/Metodologias.md
      - Cronograma do Projeto: Planejamento/Cronograma/Cronograma.md
      - Processo de Design: Planejamento/Processo/Processo.md
  - Análise de Requisitos:
      - Perfil de usuário: Análise_de_requisitos/Perfil_do_usuario/perfil_do_usuario.md
      - Personas: Análise_de_requisitos/Personas/personas.md
      - Análise de Tarefas:
          - CTT: Análise_de_requisitos/Análise_de_tarefas/CTT.md
          - HTA: Análise_de_requisitos/Análise_de_tarefas/HTA.md
      - Princípios Gerais: Análise_de_requisitos/Principios_gerais/Principios_gerais.md
      - Guia de Estilo: Análise_de_requisitos/Guia_de_estilo/guia_de_estilo.md
      - Metas de Usabilidade: Análise_de_requisitos/Metas_de_usabilidade/metas_de_usabilidade.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Análise de Tarefas:
              - Planejamento da Avaliação de Análise de Tarefas: Avaliação_desenvolvimento/Nivel1/planejamento.md
              - Entrevista: Avaliação_desenvolvimento/Nivel1/entrevista.md
              - Relato dos Resultados da Avaliação de Análise de Tarefas:
                  - Planejamento do Relato - Análise de Tarefas: Avaliação_desenvolvimento/Nivel1/planejamento_relato_analise_tarefas.md
                  - Avaliação da Tarefa 1: Avaliação_desenvolvimento/Nivel1/avaliacao1.md
                  - Avaliação da Tarefa 2: Avaliação_desenvolvimento/Nivel1/avaliacao2.md
          - Storyboard:
              - Planejamento da Avaliação - Storyboard: Avaliação_desenvolvimento/Nivel1/planejamento_storyboard.md
              - Storyboard: Avaliação_desenvolvimento/Nivel1/Storyboard.md
              - Relato dos resultados da avaliação do Storyboard: Avaliação_desenvolvimento/Nivel1/avaliacao_storyboard.md
              - Entrevistas:
                  - Entrevista 1: Avaliação_desenvolvimento/Nivel1/entrevista1.md
                  - Entrevista 2: Avaliação_desenvolvimento/Nivel1/entrevista2.md
                  - Entrevista 3: Avaliação_desenvolvimento/Nivel1/entrevista3.md
      - Nível 2:
          - Protótipo de papel:
              - Planejamento da Avaliação - Protótipo de papel: Avaliação_desenvolvimento/Nivel2/planejamento_prótipo_papel.md
              - Protótipo de baixa fidelidade: Avaliação_desenvolvimento/Nivel2/prototipo_baixa_fidelidade.md
              - Planejamento do relato: Avaliação_desenvolvimento/Nivel2/Planejamento_relato.md
              - Relato dos resultados da avaliação do Protótipo de papel: Avaliação_desenvolvimento/Nivel2/relato_resultados.md
  - Verificação:
      - Verificação: Verificação/verificacao.md
      - Perfil do Usuário: Verificação/perfil_do_usuario.md
      - Avaliação da tarefa 1: Verificação/avaliacao_da_T1.md
      - Avaliação da tarefa 2: Verificação/avaliacao_da_T2.md
      - Entrevista da Análise de Tarefas: Verificação/entrevista.md
      - Entrevista 1 do Storyboard: Verificação/entrevista_1.md
      - Entrevista 2 do Storyboard: Verificação/entrevista_2.md
      - Entrevista 3 do Storyboard: Verificação/entrevista_3.md
      - Personas: Verificação/Personas.md
      - Guia de estilo: Verificação/Guia_de_estilo.md
      - Storyboard: Verificação/Storyboard.md
      - Protótipo de baixa fidelidade: Verificação/Prototipo_baixa_fidelidade.md
      - CTT: Verificação/ctt.md
      - HTA: Verificação/hta.md
      - Metas de Usabilidade: Verificação/meta_de_usabilidade.md
      - Planejamento da Avaliação do Protótipo de Papel: Verificação/planejamento_avaliacao_papel.md
      - Planejamento da Avaliação da Análise de Tarefas: Verificação/planejamento_av_análise_de_tarefas.md
      - Planejamento da Avaliação do Storyboard: Verificação/planejamento_av_storyboard.md
      - Planejamento do Relato - Protótipo de Papel: Verificação/planejamento_do_relato.md
      - Planejamento do Relato - Análise de Tarefas: Verificação/planejamento_do_relato_analise_tarefas.md
      - Princípios Gerais: Verificação/principios_gerais.md
      - Relato dos Resultados do Storyboard: Verificação/relato_resultados_storyboard.md

  - Apresentações:
      - Apresentação 1: Apresentacoes/Apresentacao1.md
      - Apresentação 2: Apresentacoes/Apresentacao2.md
      - Apresentação 3: Apresentacoes/Apresentacao3.md
      - Apresentação 4: Apresentacoes/Apresentacao4.md
      - Apresentação 5: Apresentacoes/Apresentacao5.md
      - Apresentação 6: Apresentacoes/Apresentacao6.md
  - Atas:
      - 23-02-2022: Atas/23-02-2022.md
      - 07-03-2022: Atas/07-03-2022.md
      - 14-03-2022: Atas/14-03-2022.md
      - 04-04-2022: Atas/04-04-2022.md
      - 06-04-2022: Atas/06-04-2022.md
